insert into adresa (idadr, grad, drzava, ulica, brojulice) values (1, 'Doroslovo', 'Serbia', '2574 Transport Point', '6459');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (2, 'Lajkovac', 'Serbia', '00569 Parkside Drive', '22508');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (3, 'Turija', 'Serbia', '28 Main Circle', '68');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (4, 'Bukor', 'Serbia', '0018 Green Ridge Alley', '76620');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (5, 'Biljača', 'Serbia', '2 Veith Circle', '4307');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (6, 'Banatska Topola', 'Serbia', '08722 Victoria Pass', '2076');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (7, 'Srpska Crnja', 'Serbia', '45 Service Avenue', '18');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (8, 'Požarevac', 'Serbia', '03 Rigney Pass', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (9, 'Bečej', 'Serbia', '89723 Arizona Alley', '0926');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (10, 'Novi Bečej', 'Serbia', '971 Birchwood Way', '544');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (11, 'Bečmen', 'Serbia', '7 Corben Crossing', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (12, 'Bečej', 'Serbia', '5182 Monument Trail', '52');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (13, 'Novi Itebej', 'Serbia', '1253 Bayside Terrace', '18');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (14, 'Zvezdara', 'Serbia', '5002 Norway Maple Trail', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (15, 'Riđica', 'Serbia', '84 Pleasure Road', '40977');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (16, 'Banatska Topola', 'Serbia', '98402 Bluestem Drive', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (17, 'Boljevci', 'Serbia', '6132 Esch Circle', '76085');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (18, 'Valjevo', 'Serbia', '7892 Carey Drive', '943');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (19, 'Kruševac', 'Serbia', '29817 Eastlawn Road', '321');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (20, 'Novi Bečej', 'Serbia', '6 Manitowish Parkway', '489');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (21, 'Prislonica', 'Serbia', '222 West Plaza', '2138');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (22, 'Riđica', 'Serbia', '535 Bobwhite Parkway', '569');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (23, 'Subotica', 'Serbia', '924 Sunfield Crossing', '3796');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (24, 'Klenje', 'Serbia', '67 Ridgeway Crossing', '5572');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (25, 'Novi Kneževac', 'Serbia', '959 Prairieview Avenue', '94264');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (26, 'Leskovac', 'Serbia', '00 Oak Valley Junction', '01148');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (27, 'Riđica', 'Serbia', '32955 Hoard Pass', '61');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (28, 'Sonta', 'Serbia', '5470 1st Place', '8973');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (29, 'Lajkovac', 'Serbia', '2 Luster Pass', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (30, 'Bečej', 'Serbia', '2 Onsgard Park', '903');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (31, 'Svilajnac', 'Serbia', '120 North Plaza', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (32, 'Vranje', 'Serbia', '2 Huxley Place', '534');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (33, 'Negotin', 'Serbia', '1150 Brickson Park Place', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (34, 'Perlez', 'Serbia', '6649 Tennyson Court', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (35, 'Sajan', 'Serbia', '2865 Union Circle', '94342');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (36, 'Bački Breg', 'Serbia', '93 Duke Crossing', '661');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (37, 'Vranje', 'Serbia', '68 Calypso Plaza', '67911');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (38, 'Bačka Topola', 'Serbia', '2509 Buell Pass', '88763');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (39, 'Majur', 'Serbia', '0791 Troy Street', '997');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (40, 'Despotovac', 'Serbia', '01 Pond Hill', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (41, 'Turija', 'Serbia', '23318 Lien Avenue', '01588');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (42, 'Varna', 'Serbia', '316 Brown Point', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (43, 'Jaša Tomić', 'Serbia', '7888 Kensington Street', '481');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (44, 'Belgrade', 'Serbia', '7 Jay Junction', '66');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (45, 'Zrenjanin', 'Serbia', '07 Manufacturers Road', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (46, 'Smederevo', 'Serbia', '57238 Grasskamp Alley', '74');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (47, 'Padej', 'Serbia', '573 Cody Point', '951');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (48, 'Sombor', 'Serbia', '3677 Maple Terrace', '49072');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (49, 'Radenković', 'Serbia', '66 Moland Court', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (50, 'Šimanovci', 'Serbia', '16 7th Drive', '20');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (51, 'Banatsko Karađorđevo', 'Serbia', '38 Tennessee Pass', '373');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (52, 'Bački Petrovac', 'Serbia', '12148 Doe Crossing Pass', '787');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (53, 'Seleuš', 'Serbia', '92 Green Court', '2128');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (54, 'Novi Sad', 'Serbia', '2 Clemons Court', '69702');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (55, 'Novi Bečej', 'Serbia', '952 Burrows Alley', '55');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (56, 'Vršac', 'Serbia', '3993 Farwell Park', '8662');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (57, 'Senta', 'Serbia', '2 Northridge Junction', '3234');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (58, 'Prislonica', 'Serbia', '315 Lindbergh Trail', '5436');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (59, 'Knjazevac', 'Serbia', '374 Badeau Point', '53906');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (60, 'Draginje', 'Serbia', '96 Mcbride Alley', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (61, 'Novi Pazar', 'Serbia', '9 Mcbride Avenue', '1372');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (62, 'Duboka', 'Serbia', '346 Tennessee Trail', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (63, 'Kruševac', 'Serbia', '02 Waxwing Pass', '78');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (64, 'Aleksandrovac', 'Serbia', '3115 Mockingbird Place', '57714');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (65, 'Štitar', 'Serbia', '69137 Oak Crossing', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (66, 'Leskovac', 'Serbia', '07231 Lyons Crossing', '1819');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (67, 'Pančevo', 'Serbia', '6 Annamark Park', '543');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (68, 'Majur', 'Serbia', '1 Meadow Ridge Way', '43');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (69, 'Hrtkovci', 'Serbia', '4755 Prentice Hill', '6156');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (70, 'Požarevac', 'Serbia', '7 Boyd Drive', '683');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (71, 'Leskovac', 'Serbia', '4792 Sutteridge Way', '26793');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (72, 'Radojevo', 'Serbia', '9 Cascade Circle', '6912');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (73, 'Ćuprija', 'Serbia', '61667 Springs Plaza', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (74, 'Tomaševac', 'Serbia', '11 Transport Alley', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (75, 'Banatsko Veliko Selo', 'Serbia', '4 Schiller Drive', '422');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (76, 'Jagodina', 'Serbia', '43482 Anzinger Alley', '81294');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (77, 'Bečej', 'Serbia', '03945 Loomis Alley', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (78, 'Zaječar', 'Serbia', '0176 Novick Junction', '75178');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (79, 'Dimitrovgrad', 'Serbia', '96 Bunker Hill Lane', '77');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (80, 'Klenak', 'Serbia', '4862 Corben Avenue', '9299');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (81, 'Sremčica', 'Serbia', '1 Cottonwood Parkway', '76');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (82, 'Bečej', 'Serbia', '0325 Basil Center', '0470');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (83, 'Kovilj', 'Serbia', '18 Oakridge Terrace', '5446');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (84, 'Prokuplje', 'Serbia', '7440 Johnson Way', '2978');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (85, 'Ljubovija', 'Serbia', '68949 Grover Court', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (86, 'Leskovac', 'Serbia', '0159 Browning Trail', '0682');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (87, 'Bečej', 'Serbia', '9210 Oak Valley Plaza', '219');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (88, 'Seleuš', 'Serbia', '2044 Sauthoff Place', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (89, 'Bojnik', 'Serbia', '5 Cody Parkway', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (90, 'Gardinovci', 'Serbia', '87 Weeping Birch Drive', '22');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (91, 'Svilajnac', 'Serbia', '70 Spohn Junction', '33970');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (92, 'Doroslovo', 'Serbia', '1 Clove Place', '76730');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (93, 'Kupusina', 'Serbia', '7 Kennedy Hill', '25');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (94, 'Šimanovci', 'Serbia', '1280 Westend Park', '162');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (95, 'Turija', 'Serbia', '736 Oneill Circle', '50231');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (96, 'Veternik', 'Serbia', '1 Calypso Drive', '945');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (97, 'Čoka', 'Serbia', '620 Northfield Terrace', '5004');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (98, 'Ostružnica', 'Serbia', '7620 Lakewood Point', '797');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (99, 'Neuzina', 'Serbia', '649 Pine View Court', '1399');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (100, 'Klenak', 'Serbia', '60565 Artisan Trail', '235');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (101, 'Kladovo', 'Serbia', '52814 Schlimgen Crossing', '26');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (102, 'Smederevska Palanka', 'Serbia', '367 Bonner Parkway', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (103, 'Smederevska Palanka', 'Serbia', '16 Fremont Center', '60254');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (104, 'Dobrica', 'Serbia', '355 Pierstorff Park', '00');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (105, 'Bečej', 'Serbia', '8143 Main Crossing', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (106, 'Višnjićevo', 'Serbia', '08186 Autumn Leaf Pass', '32158');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (107, 'Šabac', 'Serbia', '1 Blue Bill Park Avenue', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (108, 'Inđija', 'Serbia', '06487 Delaware Park', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (109, 'Jazovo', 'Serbia', '0 Vidon Lane', '36');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (110, 'Rumenka', 'Serbia', '240 Toban Junction', '7585');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (111, 'Banatski Dvor', 'Serbia', '5 Farwell Street', '170');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (112, 'Radenković', 'Serbia', '7 Mifflin Lane', '69');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (113, 'Novi Slankamen', 'Serbia', '202 Clove Center', '82481');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (114, 'Stari Lec', 'Serbia', '0 Mitchell Terrace', '47613');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (115, 'Lok', 'Serbia', '99107 Commercial Avenue', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (116, 'Aleksandrovac', 'Serbia', '54 Buell Alley', '33');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (117, 'Jermenovci', 'Serbia', '04836 Cascade Crossing', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (118, 'Nikinci', 'Serbia', '25380 Iowa Park', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (119, 'Bečmen', 'Serbia', '5 Atwood Center', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (120, 'Pirot', 'Serbia', '05 Westridge Place', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (121, 'Farkaždin', 'Serbia', '0 Meadow Vale Park', '9508');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (122, 'Bački Breg', 'Serbia', '3 Milwaukee Parkway', '8655');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (123, 'Bačka Topola', 'Serbia', '3 Veith Center', '66768');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (124, 'Kikinda', 'Serbia', '24003 Granby Court', '66690');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (125, 'Ljig', 'Serbia', '9 Truax Street', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (126, 'Debeljača', 'Serbia', '651 Tony Street', '922');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (127, 'Ćuprija', 'Serbia', '99 Hanover Crossing', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (128, 'Šimanovci', 'Serbia', '789 Hagan Court', '48');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (129, 'Aleksandrovac', 'Serbia', '7518 Esker Parkway', '9592');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (130, 'Dublje', 'Serbia', '8167 Kensington Point', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (131, 'Padina', 'Serbia', '63 Anniversary Hill', '22891');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (132, 'Banovo Polje', 'Serbia', '55 Forest Drive', '74056');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (133, 'Knjazevac', 'Serbia', '68092 Weeping Birch Alley', '4990');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (134, 'Topola', 'Serbia', '57679 Green Ridge Point', '1949');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (135, 'Čajetina', 'Serbia', '97616 Loeprich Hill', '86');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (136, 'Niš', 'Serbia', '792 Thackeray Hill', '54');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (137, 'Platičevo', 'Serbia', '92 Anthes Crossing', '923');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (138, 'Koceljeva', 'Serbia', '4528 Tennyson Parkway', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (139, 'Pirot', 'Serbia', '56728 Artisan Plaza', '690');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (140, 'Margita', 'Serbia', '6327 Claremont Crossing', '88');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (141, 'Nakovo', 'Serbia', '95186 Corscot Drive', '28433');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (142, 'Lebane', 'Serbia', '2 Hovde Place', '35406');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (143, 'Koceljeva', 'Serbia', '47 Karstens Alley', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (144, 'Novi Sad', 'Serbia', '29 Morning Court', '8178');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (145, 'Tršić', 'Serbia', '1356 Hintze Drive', '33718');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (146, 'Ostružnica', 'Serbia', '02 Aberg Avenue', '4821');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (147, 'Stanišić', 'Serbia', '6236 Eagan Court', '07');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (148, 'Pančevo', 'Serbia', '515 Hollow Ridge Pass', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (149, 'Smederevo', 'Serbia', '8 Grover Circle', '24317');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (150, 'Bujanovac', 'Serbia', '93 Dottie Crossing', '2390');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (151, 'Beška', 'Serbia', '97 Tennyson Court', '71');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (152, 'Dobrica', 'Serbia', '46 Farragut Junction', '76');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (153, 'Inđija', 'Serbia', '07 Coleman Trail', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (154, 'Belo Blato', 'Serbia', '29961 Badeau Court', '3369');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (155, 'Lok', 'Serbia', '95 Monument Pass', '3736');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (156, 'Rekovac', 'Serbia', '48661 Reindahl Crossing', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (157, 'Banatsko Karađorđevo', 'Serbia', '7208 Basil Terrace', '37');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (158, 'Inđija', 'Serbia', '70 Green Street', '821');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (159, 'Novi Beograd', 'Serbia', '885 Hanson Circle', '2360');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (160, 'Čoka', 'Serbia', '2883 Dorton Drive', '6580');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (161, 'Banovo Polje', 'Serbia', '89 Bonner Avenue', '7206');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (162, 'Zemun', 'Serbia', '1928 Eggendart Court', '18327');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (163, 'Užice', 'Serbia', '7 Green Trail', '48');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (164, 'Gornji Breg', 'Serbia', '56732 Mosinee Street', '0091');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (165, 'Medveđa', 'Serbia', '7 Claremont Alley', '18');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (166, 'Bukor', 'Serbia', '972 Waubesa Road', '5977');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (167, 'Priboj', 'Serbia', '1 Gale Pass', '5736');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (168, 'Bor', 'Serbia', '4 Menomonie Trail', '84');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (169, 'Ševica', 'Serbia', '7 Starling Lane', '16');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (170, 'Novi Pazar', 'Serbia', '5365 Delladonna Court', '532');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (171, 'Kruševac', 'Serbia', '39 Lunder Way', '11658');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (172, 'Platičevo', 'Serbia', '64 Knutson Parkway', '898');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (173, 'Bačka Topola', 'Serbia', '6239 Toban Point', '65932');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (174, 'Kumane', 'Serbia', '93 Butterfield Road', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (175, 'Čačak', 'Serbia', '87904 Warner Circle', '2112');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (176, 'Leskovac', 'Serbia', '8502 Vermont Point', '25542');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (177, 'Aleksinac', 'Serbia', '022 Rieder Avenue', '89');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (178, 'Kamenica', 'Serbia', '28 Hooker Street', '5147');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (179, 'Bačka Topola', 'Serbia', '8932 Eliot Drive', '546');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (180, 'Palilula', 'Serbia', '35111 Kings Avenue', '6185');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (181, 'Novi Karlovci', 'Serbia', '0 Reindahl Lane', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (182, 'Leskovac', 'Serbia', '56148 Clemons Plaza', '5543');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (183, 'Međa', 'Serbia', '06170 Havey Avenue', '183');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (184, 'Bačka Topola', 'Serbia', '5 Washington Road', '26812');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (185, 'Donji Dobrić', 'Serbia', '62882 Ohio Terrace', '97');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (186, 'Aranđelovac', 'Serbia', '734 Jackson Crossing', '08');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (187, 'Lajkovac', 'Serbia', '78430 Victoria Circle', '5870');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (188, 'Mali Iđoš', 'Serbia', '7 Bluestem Avenue', '3434');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (189, 'Smederevska Palanka', 'Serbia', '5051 Mayfield Lane', '18944');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (190, 'Šid', 'Serbia', '44 Vernon Drive', '6527');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (191, 'Zvezdara', 'Serbia', '706 Crest Line Alley', '0091');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (192, 'Savski Venac', 'Serbia', '0827 Vernon Park', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (193, 'Novi Beograd', 'Serbia', '1873 Mandrake Avenue', '03717');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (194, 'Trstenik', 'Serbia', '738 Monterey Place', '4414');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (195, 'Mali Iđoš', 'Serbia', '93 2nd Drive', '8');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (196, 'Kladovo', 'Serbia', '669 Summit Junction', '2997');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (197, 'Kulpin', 'Serbia', '459 Dwight Parkway', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (198, 'Perlez', 'Serbia', '691 Ruskin Pass', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (199, 'Smederevska Palanka', 'Serbia', '179 Green Terrace', '8');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (200, 'Platičevo', 'Serbia', '44 Mcguire Street', '54233');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (201, 'Ljig', 'Serbia', '291 Spaight Trail', '31');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (202, 'Požarevac', 'Serbia', '12983 Tomscot Junction', '36983');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (203, 'Obrenovac', 'Serbia', '1472 Grim Way', '42179');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (204, 'Seleuš', 'Serbia', '513 Forest Run Circle', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (205, 'Požarevac', 'Serbia', '84034 Autumn Leaf Park', '48062');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (206, 'Mali Iđoš', 'Serbia', '2096 Golf View Park', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (207, 'Kumane', 'Serbia', '36937 Petterle Drive', '708');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (208, 'Šid', 'Serbia', '410 Ramsey Lane', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (209, 'Vrbas', 'Serbia', '3092 Northridge Junction', '27810');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (210, 'Jaša Tomić', 'Serbia', '734 Katie Alley', '94');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (211, 'Prigrevica', 'Serbia', '99334 Monterey Parkway', '39');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (212, 'Dimitrovgrad', 'Serbia', '94 Russell Terrace', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (213, 'Salaš Crnobarski', 'Serbia', '962 Manitowish Drive', '4568');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (214, 'Gakovo', 'Serbia', '7 Clyde Gallagher Trail', '54822');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (215, 'Tršić', 'Serbia', '87 Ridgeview Crossing', '37');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (216, 'Bojnik', 'Serbia', '1 Emmet Parkway', '5525');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (217, 'Doroslovo', 'Serbia', '1 Kinsman Alley', '2923');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (218, 'Bujanovac', 'Serbia', '363 John Wall Terrace', '9655');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (219, 'Banatski Despotovac', 'Serbia', '91 Sutherland Street', '354');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (220, 'Topola', 'Serbia', '23 Waxwing Trail', '828');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (221, 'Valjevo', 'Serbia', '1841 Roth Drive', '51');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (222, 'Ševica', 'Serbia', '171 Southridge Lane', '78');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (223, 'Vranje', 'Serbia', '56134 Claremont Plaza', '8824');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (224, 'Klenje', 'Serbia', '2622 Roxbury Lane', '121');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (225, 'Boljevci', 'Serbia', '9 Dapin Circle', '7844');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (226, 'Gakovo', 'Serbia', '9784 Mcguire Park', '1988');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (227, 'Neuzina', 'Serbia', '0 Anderson Street', '801');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (228, 'Lajkovac', 'Serbia', '21 Badeau Road', '771');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (229, 'Banatski Despotovac', 'Serbia', '84378 Harbort Hill', '903');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (230, 'Belo Blato', 'Serbia', '66019 Derek Avenue', '017');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (231, 'Novi Slankamen', 'Serbia', '958 Springview Terrace', '477');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (232, 'Lajkovac', 'Serbia', '1 Coleman Place', '708');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (233, 'Kruševac', 'Serbia', '3 Dawn Junction', '2663');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (234, 'Duboka', 'Serbia', '03 Kipling Point', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (235, 'Aradac', 'Serbia', '40450 Starling Plaza', '15');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (236, 'Svilajnac', 'Serbia', '1 Oak Valley Junction', '85638');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (237, 'Margita', 'Serbia', '3 Merry Pass', '96');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (238, 'Smederevo', 'Serbia', '0147 Huxley Place', '84414');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (239, 'Rekovac', 'Serbia', '14 Marcy Lane', '78');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (240, 'Šimanovci', 'Serbia', '72 Arkansas Trail', '525');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (241, 'Ćićevac', 'Serbia', '2 Blaine Crossing', '7640');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (242, 'Senta', 'Serbia', '26521 Colorado Plaza', '18483');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (243, 'Bačka Topola', 'Serbia', '1 Myrtle Circle', '742');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (244, 'Niš', 'Serbia', '5306 Sachtjen Plaza', '35582');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (245, 'Bečmen', 'Serbia', '9231 Sutteridge Plaza', '165');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (246, 'Knjazevac', 'Serbia', '80813 Memorial Hill', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (247, 'Obrenovac', 'Serbia', '70 Ohio Drive', '053');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (248, 'Padina', 'Serbia', '09 Northridge Street', '88457');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (249, 'Čoka', 'Serbia', '23 Logan Alley', '372');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (250, 'Idvor', 'Serbia', '1477 Prairieview Drive', '31');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (251, 'Biljača', 'Serbia', '2 Burning Wood Street', '982');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (252, 'Tomaševac', 'Serbia', '69915 Merry Plaza', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (253, 'Knjazevac', 'Serbia', '3 Hintze Park', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (254, 'Salaš Crnobarski', 'Serbia', '994 Heffernan Plaza', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (255, 'Klenje', 'Serbia', '273 Spaight Junction', '043');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (256, 'Bajina Bašta', 'Serbia', '0553 Rieder Terrace', '95986');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (257, 'Ćuprija', 'Serbia', '27532 Waywood Lane', '0925');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (258, 'Stari Banovci', 'Serbia', '2426 Duke Trail', '13');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (259, 'Ljubovija', 'Serbia', '33567 Bay Crossing', '592');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (260, 'Kladovo', 'Serbia', '58 Holy Cross Point', '62340');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (261, 'Biljača', 'Serbia', '8246 Harbort Junction', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (262, 'Mošorin', 'Serbia', '2 Springview Hill', '85720');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (263, 'Nakovo', 'Serbia', '7 Ilene Road', '032');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (264, 'Sombor', 'Serbia', '8 Bunting Junction', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (265, 'Badovinci', 'Serbia', '5094 Del Mar Avenue', '628');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (266, 'Višnjićevo', 'Serbia', '88 Upham Junction', '678');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (267, 'Tomaševac', 'Serbia', '07 Shoshone Avenue', '3709');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (268, 'Ljubovija', 'Serbia', '9 Warbler Trail', '57995');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (269, 'Stari Grad', 'Serbia', '7235 Swallow Circle', '80');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (270, 'Nova Pazova', 'Serbia', '715 Morning Way', '523');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (271, 'Belgrade', 'Serbia', '13033 Hooker Point', '78');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (272, 'Adorjan', 'Serbia', '609 Main Center', '033');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (273, 'Valjevo', 'Serbia', '250 Vera Drive', '18284');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (274, 'Joševa', 'Serbia', '380 Alpine Circle', '73');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (275, 'Bukor', 'Serbia', '517 Blaine Street', '208');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (276, 'Boka', 'Serbia', '4249 Pierstorff Road', '803');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (277, 'Smederevska Palanka', 'Serbia', '67379 Corben Terrace', '35');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (278, 'Dimitrovgrad', 'Serbia', '698 Lerdahl Place', '092');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (279, 'Gardinovci', 'Serbia', '610 Merry Place', '2479');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (280, 'Srpska Crnja', 'Serbia', '99 Chive Drive', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (281, 'Ljig', 'Serbia', '1 Park Meadow Trail', '9435');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (282, 'Bogojevo', 'Serbia', '493 Continental Parkway', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (283, 'Gložan', 'Serbia', '2414 Leroy Center', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (284, 'Kruševac', 'Serbia', '06180 Ryan Circle', '22292');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (285, 'Zvezdara', 'Serbia', '27177 Fairview Drive', '87');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (286, 'Ljubovija', 'Serbia', '8 Fulton Road', '01');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (287, 'Kupusina', 'Serbia', '69 Maple Wood Parkway', '64');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (288, 'Taraš', 'Serbia', '92 Oak Valley Pass', '70');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (289, 'Bačka Topola', 'Serbia', '84598 Grover Court', '14564');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (290, 'Padej', 'Serbia', '1415 Merrick Road', '74');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (291, 'Barajevo', 'Serbia', '7 Eastlawn Park', '745');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (292, 'Kumane', 'Serbia', '49 Glendale Court', '58184');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (293, 'Lukićevo', 'Serbia', '318 Manley Point', '47645');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (294, 'Koceljeva', 'Serbia', '97 Maywood Alley', '2302');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (295, 'Jagodina', 'Serbia', '13 Scott Circle', '19915');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (296, 'Čajetina', 'Serbia', '5367 Nova Road', '68');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (297, 'Putinci', 'Serbia', '33 Lakeland Trail', '42055');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (298, 'Subotica', 'Serbia', '4759 Delladonna Hill', '636');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (299, 'Bor', 'Serbia', '0 Troy Point', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (300, 'Bečej', 'Serbia', '20130 Eliot Pass', '7854');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (301, 'Medveđa', 'Serbia', '15648 Mayer Drive', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (302, 'Ruma', 'Serbia', '5 Riverside Terrace', '956');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (303, 'Prokuplje', 'Serbia', '871 Hazelcrest Crossing', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (304, 'Kuštilj', 'Serbia', '3 Dennis Circle', '9473');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (305, 'Donji Dobrić', 'Serbia', '9 Autumn Leaf Drive', '8582');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (306, 'Novi Beograd', 'Serbia', '2906 Lighthouse Bay Way', '99');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (307, 'Kuštilj', 'Serbia', '42213 Warbler Crossing', '23784');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (308, 'Kučevo', 'Serbia', '60 Washington Park', '214');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (309, 'Golubac', 'Serbia', '13 Homewood Road', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (310, 'Badovinci', 'Serbia', '452 Riverside Center', '05116');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (311, 'Užice', 'Serbia', '422 Shelley Trail', '21107');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (312, 'Bačka Topola', 'Serbia', '15 Lawn Center', '31075');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (313, 'Jermenovci', 'Serbia', '2 Thierer Parkway', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (314, 'Topola', 'Serbia', '7999 Redwing Terrace', '126');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (315, 'Bačka Topola', 'Serbia', '95 Claremont Pass', '3535');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (316, 'Bašaid', 'Serbia', '9 Iowa Drive', '67');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (317, 'Nikolinci', 'Serbia', '5704 Hayes Street', '86');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (318, 'Nikinci', 'Serbia', '5 Dayton Alley', '948');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (319, 'Višnjićevo', 'Serbia', '0566 Sutteridge Junction', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (320, 'Boka', 'Serbia', '95 High Crossing Crossing', '204');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (321, 'Uzdin', 'Serbia', '79 Debs Street', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (322, 'Biljača', 'Serbia', '0 Pankratz Drive', '815');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (323, 'Paraćin', 'Serbia', '3760 Little Fleur Center', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (324, 'Nova Varoš', 'Serbia', '3 Gale Crossing', '94479');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (325, 'Kamenica', 'Serbia', '286 Farwell Center', '59300');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (326, 'Pavliš', 'Serbia', '5362 Trailsway Point', '52');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (327, 'Jaša Tomić', 'Serbia', '743 Dottie Junction', '98092');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (328, 'Banatsko Karađorđevo', 'Serbia', '2 Northland Point', '7363');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (329, 'Smederevo', 'Serbia', '9 Sachs Alley', '623');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (330, 'Donji Dobrić', 'Serbia', '00867 Leroy Circle', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (331, 'Badovinci', 'Serbia', '6805 Fisk Street', '81');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (332, 'Gornji Breg', 'Serbia', '97 Saint Paul Plaza', '961');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (333, 'Kraljevo', 'Serbia', '24 Brentwood Point', '06');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (334, 'Sakule', 'Serbia', '02 Crownhardt Trail', '25');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (335, 'Putinci', 'Serbia', '57 Brown Alley', '8');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (336, 'Lajkovac', 'Serbia', '390 Shopko Lane', '4679');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (337, 'Kupusina', 'Serbia', '86 Packers Trail', '3334');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (338, 'Kuštilj', 'Serbia', '4 Norway Maple Park', '2703');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (339, 'Stari Banovci', 'Serbia', '21 Doe Crossing Park', '61458');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (340, 'Svilajnac', 'Serbia', '594 Ilene Street', '86');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (341, 'Kraljevo', 'Serbia', '074 Bobwhite Place', '50');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (342, 'Koceljeva', 'Serbia', '518 Thompson Junction', '442');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (343, 'Belgrade', 'Serbia', '4 Duke Plaza', '48585');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (344, 'Smederevo', 'Serbia', '4113 Golf View Terrace', '34');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (345, 'Čoka', 'Serbia', '3687 Truax Pass', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (346, 'Šimanovci', 'Serbia', '33 Homewood Junction', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (347, 'Bočar', 'Serbia', '1478 Prairieview Court', '954');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (348, 'Bačka Palanka', 'Serbia', '9362 Weeping Birch Trail', '6522');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (349, 'Riđica', 'Serbia', '9 Dunning Crossing', '48841');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (350, 'Novi Beograd', 'Serbia', '8 Ohio Lane', '3340');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (351, 'Riđica', 'Serbia', '30938 Old Gate Road', '09223');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (352, 'Doljevac', 'Serbia', '5195 Hovde Circle', '75');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (353, 'Ljukovo', 'Serbia', '6704 Kensington Street', '9675');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (354, 'Nova Varoš', 'Serbia', '084 Truax Lane', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (355, 'Leskovac', 'Serbia', '36 Burrows Trail', '92');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (356, 'Banatska Topola', 'Serbia', '326 Florence Point', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (357, 'Senta', 'Serbia', '5 Jenna Place', '100');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (358, 'Padej', 'Serbia', '135 Thompson Center', '981');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (359, 'Kupusina', 'Serbia', '8 Iowa Way', '07');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (360, 'Ljig', 'Serbia', '762 Atwood Road', '58152');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (361, 'Prigrevica', 'Serbia', '700 Myrtle Trail', '76061');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (362, 'Knjazevac', 'Serbia', '8949 Graedel Plaza', '628');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (363, 'Rača', 'Serbia', '433 Brentwood Place', '05');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (364, 'Sonta', 'Serbia', '2415 Coleman Parkway', '269');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (365, 'Stanišić', 'Serbia', '904 Lyons Hill', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (366, 'Nova Pazova', 'Serbia', '8 Granby Place', '9627');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (367, 'Krivaja', 'Serbia', '33004 Leroy Street', '54');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (368, 'Sonta', 'Serbia', '5 Main Plaza', '8770');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (369, 'Mali Iđoš', 'Serbia', '52396 Marquette Hill', '7090');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (370, 'Kučevo', 'Serbia', '750 Havey Plaza', '884');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (371, 'Inđija', 'Serbia', '90031 Amoth Parkway', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (372, 'Biljača', 'Serbia', '3 Pearson Avenue', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (373, 'Nakovo', 'Serbia', '3255 Charing Cross Hill', '75');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (374, 'Bačka Palanka', 'Serbia', '15799 Pleasure Center', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (375, 'Gardinovci', 'Serbia', '56455 Arizona Road', '65');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (376, 'Klek', 'Serbia', '0816 Stone Corner Plaza', '7379');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (377, 'Gakovo', 'Serbia', '56 Troy Drive', '08462');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (378, 'Inđija', 'Serbia', '77681 Division Circle', '90194');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (379, 'Čortanovci', 'Serbia', '88 Golf View Junction', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (380, 'Gudurica', 'Serbia', '3279 Autumn Leaf Lane', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (381, 'Savski Venac', 'Serbia', '948 Bartillon Parkway', '6846');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (382, 'Pančevo', 'Serbia', '614 Forest Run Circle', '52375');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (383, 'Lukićevo', 'Serbia', '56 Mendota Pass', '4549');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (384, 'Stepanovićevo', 'Serbia', '46 Eastlawn Circle', '6032');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (385, 'Stari Banovci', 'Serbia', '685 8th Parkway', '13457');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (386, 'Bogojevo', 'Serbia', '9 Del Mar Court', '86989');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (387, 'Radenka', 'Serbia', '092 Harper Park', '151');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (388, 'Bačka Palanka', 'Serbia', '46228 Division Junction', '53582');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (389, 'Aranđelovac', 'Serbia', '9861 Vera Alley', '428');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (390, 'Novi Bečej', 'Serbia', '34783 Golden Leaf Alley', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (391, 'Niška Banja', 'Serbia', '51 Fairfield Center', '05535');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (392, 'Kupusina', 'Serbia', '6 Anderson Place', '40723');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (393, 'Jazovo', 'Serbia', '419 Roxbury Point', '1675');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (394, 'Zvezdara', 'Serbia', '10 Sutteridge Junction', '881');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (395, 'Seleuš', 'Serbia', '60487 Burning Wood Junction', '41159');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (396, 'Gornji Milanovac', 'Serbia', '8007 Oak Valley Avenue', '9');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (397, 'Boka', 'Serbia', '1085 East Drive', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (398, 'Ostojićevo', 'Serbia', '89854 Anhalt Place', '983');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (399, 'Perlez', 'Serbia', '8332 Burrows Alley', '3438');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (400, 'Bački Breg', 'Serbia', '7 Hoepker Circle', '80');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (401, 'Lazarevac', 'Serbia', '00533 Corscot Place', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (402, 'Ćuprija', 'Serbia', '6 Donald Street', '43');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (403, 'Gornji Milanovac', 'Serbia', '2 Marquette Terrace', '730');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (404, 'Vranje', 'Serbia', '7 Union Parkway', '879');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (405, 'Zrenjanin', 'Serbia', '8 Hanson Road', '202');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (406, 'Rekovac', 'Serbia', '1889 Rusk Terrace', '7448');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (407, 'Šid', 'Serbia', '62 Ilene Trail', '14');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (408, 'Kula', 'Serbia', '0803 Larry Circle', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (409, 'Mošorin', 'Serbia', '731 Kipling Center', '3795');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (410, 'Šimanovci', 'Serbia', '7530 Hallows Circle', '718');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (411, 'Mošorin', 'Serbia', '40340 Loeprich Drive', '54');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (412, 'Aleksinac', 'Serbia', '097 Pleasure Park', '316');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (413, 'Nikinci', 'Serbia', '23312 Stang Pass', '66083');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (414, 'Obrenovac', 'Serbia', '7 Randy Plaza', '4145');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (415, 'Sremčica', 'Serbia', '791 Oxford Street', '55');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (416, 'Gornji Breg', 'Serbia', '13013 Esch Place', '955');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (417, 'Bočar', 'Serbia', '7829 Autumn Leaf Park', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (418, 'Novi Sad', 'Serbia', '4984 Village Parkway', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (419, 'Dobrica', 'Serbia', '88 Amoth Avenue', '8077');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (420, 'Stanišić', 'Serbia', '7037 Miller Terrace', '684');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (421, 'Požarevac', 'Serbia', '88951 Erie Terrace', '33408');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (422, 'Joševa', 'Serbia', '29701 Rusk Court', '9321');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (423, 'Banatski Despotovac', 'Serbia', '4 Cascade Circle', '8528');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (424, 'Ostojićevo', 'Serbia', '7 Sutherland Trail', '77');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (425, 'Radenka', 'Serbia', '8 Debra Plaza', '7975');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (426, 'Sonta', 'Serbia', '5915 Maple Alley', '76');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (427, 'Vrbas', 'Serbia', '4 Beilfuss Drive', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (428, 'Šabac', 'Serbia', '82 Northland Junction', '137');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (429, 'Jevremovac', 'Serbia', '80989 Merry Hill', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (430, 'Svrljig', 'Serbia', '90 Pond Center', '3');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (431, 'Bačka Topola', 'Serbia', '62 Crowley Terrace', '12');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (432, 'Adorjan', 'Serbia', '8 Sutherland Pass', '7756');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (433, 'Stari Grad', 'Serbia', '006 Waywood Point', '854');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (434, 'Topola', 'Serbia', '6234 Oak Valley Drive', '8');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (435, 'Kruševac', 'Serbia', '69 Springview Center', '44610');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (436, 'Mali Iđoš', 'Serbia', '2947 Summer Ridge Point', '5');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (437, 'Čortanovci', 'Serbia', '6271 Westerfield Park', '501');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (438, 'Leskovac', 'Serbia', '317 Jenifer Drive', '39766');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (439, 'Bačka Palanka', 'Serbia', '00451 Westridge Parkway', '35');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (440, 'Pirot', 'Serbia', '09 Luster Plaza', '32');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (441, 'Požarevac', 'Serbia', '2170 Main Parkway', '8697');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (442, 'Seleuš', 'Serbia', '8 Bunker Hill Drive', '3369');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (443, 'Sombor', 'Serbia', '84 Vahlen Parkway', '96649');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (444, 'Varna', 'Serbia', '49129 Meadow Valley Crossing', '19');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (445, 'Dimitrovgrad', 'Serbia', '140 Cherokee Way', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (446, 'Međa', 'Serbia', '490 Longview Junction', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (447, 'Stara Pazova', 'Serbia', '25 Artisan Court', '853');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (448, 'Zvezdara', 'Serbia', '35 Arkansas Junction', '84');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (449, 'Ruma', 'Serbia', '86 Crowley Junction', '8');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (450, 'Klenje', 'Serbia', '8201 Ridgeview Hill', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (451, 'Savski Venac', 'Serbia', '0 Sheridan Crossing', '0018');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (452, 'Lok', 'Serbia', '90268 Everett Parkway', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (453, 'Inđija', 'Serbia', '859 Northland Hill', '88388');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (454, 'Savski Venac', 'Serbia', '014 Orin Street', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (455, 'Koceljeva', 'Serbia', '88 Summit Parkway', '028');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (456, 'Jazovo', 'Serbia', '44 Calypso Point', '4');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (457, 'Inđija', 'Serbia', '4 Schmedeman Drive', '96426');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (458, 'Kovilj', 'Serbia', '28 Hauk Drive', '02');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (459, 'Farkaždin', 'Serbia', '23 Cambridge Avenue', '5803');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (460, 'Kraljevo', 'Serbia', '37 Ruskin Avenue', '41');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (461, 'Bujanovac', 'Serbia', '3340 Calypso Plaza', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (462, 'Novi Slankamen', 'Serbia', '6 Forest Run Junction', '2');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (463, 'Doljevac', 'Serbia', '69 Pearson Avenue', '31908');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (464, 'Despotovac', 'Serbia', '1 Carpenter Pass', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (465, 'Veternik', 'Serbia', '6905 Morrow Drive', '092');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (466, 'Debeljača', 'Serbia', '6622 Harper Plaza', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (467, 'Dimitrovgrad', 'Serbia', '256 Golden Leaf Drive', '24');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (468, 'Bačka Topola', 'Serbia', '08656 Milwaukee Drive', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (469, 'Varna', 'Serbia', '6 Fremont Crossing', '9049');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (470, 'Kupusina', 'Serbia', '30206 Meadow Ridge Trail', '855');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (471, 'Lukićevo', 'Serbia', '01770 Golf Crossing', '91');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (472, 'Buđanovci', 'Serbia', '9 Sullivan Park', '3713');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (473, 'Bočar', 'Serbia', '12315 Manufacturers Way', '16');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (474, 'Gudurica', 'Serbia', '4689 Crest Line Avenue', '5473');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (475, 'Ljukovo', 'Serbia', '5227 Straubel Circle', '529');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (476, 'Prigrevica', 'Serbia', '77768 Menomonie Point', '3493');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (477, 'Novi Karlovci', 'Serbia', '42 Blackbird Court', '9005');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (478, 'Vršac', 'Serbia', '69478 Briar Crest Hill', '2617');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (479, 'Seleuš', 'Serbia', '91095 Kenwood Crossing', '834');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (480, 'Ruma', 'Serbia', '42 Delaware Point', '70');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (481, 'Lajkovac', 'Serbia', '15677 Nova Junction', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (482, 'Niš', 'Serbia', '9845 Becker Pass', '8291');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (483, 'Neuzina', 'Serbia', '5089 Goodland Place', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (484, 'Orlovat', 'Serbia', '05287 Bartillon Road', '7');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (485, 'Gornji Milanovac', 'Serbia', '3 Northland Alley', '10862');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (486, 'Kamenica', 'Serbia', '76482 Crowley Lane', '4375');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (487, 'Novi Kneževac', 'Serbia', '254 Eagan Way', '68691');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (488, 'Golubac', 'Serbia', '87 Surrey Crossing', '6267');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (489, 'Stepojevac', 'Serbia', '34 Merchant Alley', '41');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (490, 'Belgrade', 'Serbia', '041 Kipling Junction', '0');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (491, 'Sonta', 'Serbia', '33736 Roxbury Alley', '74465');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (492, 'Smederevo', 'Serbia', '31580 Nevada Terrace', '1');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (493, 'Ljubovija', 'Serbia', '61025 Goodland Crossing', '82353');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (494, 'Stari Banovci', 'Serbia', '014 Raven Place', '6');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (495, 'Aranđelovac', 'Serbia', '03939 Bayside Way', '687');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (496, 'Inđija', 'Serbia', '8863 Waywood Circle', '88210');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (497, 'Valjevo', 'Serbia', '863 Green Ridge Parkway', '4001');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (498, 'Požarevac', 'Serbia', '8 Lunder Drive', '87');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (499, 'Savski Venac', 'Serbia', '33 Clarendon Pass', '30353');
insert into adresa (idadr, grad, drzava, ulica, brojulice) values (500, 'Ćićevac', 'Serbia', '175 Brickson Park Point', '83');
