-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-23 18:35:42 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE admin (
    idr INTEGER NOT NULL
);

ALTER TABLE admin ADD CONSTRAINT admin_pk PRIMARY KEY ( idr );

CREATE TABLE adresa (
    idadr     INTEGER NOT NULL,
    grad      VARCHAR2(50) NOT NULL,
    drzava    VARCHAR2(50) NOT NULL,
    ulica     VARCHAR2(50) NOT NULL,
    brojulice VARCHAR2(50) NOT NULL
);

ALTER TABLE adresa ADD CONSTRAINT adresa_pk PRIMARY KEY ( idadr );

CREATE TABLE bodovna_skala (
    idbs INTEGER NOT NULL,
    idr  INTEGER NOT NULL,
    brb  INTEGER,
    idr2 INTEGER NOT NULL
);

ALTER TABLE bodovna_skala ADD CONSTRAINT bodovnaskala_pk PRIMARY KEY ( idbs );

CREATE TABLE filijala (
    idfl    INTEGER NOT NULL,
    opisfl  VARCHAR2(200) NOT NULL,
    nazivfl VARCHAR2(50),
    rbfl    VARCHAR2(50),
    idadr   INTEGER,
    idf     INTEGER
);

ALTER TABLE filijala ADD CONSTRAINT filijala_pk PRIMARY KEY ( idfl );

ALTER TABLE filijala ADD CONSTRAINT filijala__un UNIQUE ( nazivfl );

ALTER TABLE filijala ADD CONSTRAINT filijala__unv1 UNIQUE ( idadr );

CREATE TABLE firma (
    idf              INTEGER NOT NULL,
    nazivf           VARCHAR2(50) NOT NULL,
    godinaosnivanjaf DATE,
    idadr            INTEGER
);

CREATE INDEX firma__idx ON
    firma (
        idf
    ASC );

ALTER TABLE firma ADD CONSTRAINT firma_pk PRIMARY KEY ( idf );

ALTER TABLE firma ADD CONSTRAINT firma__un UNIQUE ( nazivf );

ALTER TABLE firma ADD CONSTRAINT firma__unv1 UNIQUE ( idadr );

CREATE TABLE hr (
    idr           INTEGER NOT NULL,
    strucnasprema VARCHAR2(50),
    del           VARCHAR2(50)
);

ALTER TABLE hr ADD CONSTRAINT hr_pk PRIMARY KEY ( idr );

CREATE TABLE interni_projekat (
    idp INTEGER NOT NULL,
    ids INTEGER NOT NULL
);

ALTER TABLE interni_projekat ADD CONSTRAINT interniprojekat_idp_un UNIQUE ( idp );

CREATE TABLE inzenjer_obavlja_zaduzenje (
    projekatzaduzenje_idp INTEGER NOT NULL,
    projekatzaduzenje_idz INTEGER NOT NULL,
    inzinjerprojekat_idp  INTEGER NOT NULL,
    inzinjerprojekat_idr  INTEGER NOT NULL
);

ALTER TABLE inzenjer_obavlja_zaduzenje
    ADD CONSTRAINT inzenjerobavljazaduzenje_pk PRIMARY KEY ( projekatzaduzenje_idp,
                                                             projekatzaduzenje_idz,
                                                             inzinjerprojekat_idp,
                                                             inzinjerprojekat_idr );

CREATE TABLE inzinjer_projekat (
    idr    INTEGER NOT NULL,
    idp    INTEGER NOT NULL,
    brsati INTEGER
);

ALTER TABLE inzinjer_projekat ADD CONSTRAINT inzinjerprojekat_pk PRIMARY KEY ( idr,
                                                                               idp );

CREATE TABLE klijent (
    idk  INTEGER NOT NULL,
    imek VARCHAR2(50) NOT NULL,
    przk VARCHAR2(50) NOT NULL,
    mbrk INTEGER NOT NULL
);

ALTER TABLE klijent ADD CONSTRAINT klijent_pk PRIMARY KEY ( idk );
ALTER TABLE klijent ADD CONSTRAINT klijent__un UNIQUE ( mbrk );

CREATE TABLE klijentski_projekat (
    idp INTEGER NOT NULL,
    idk INTEGER NOT NULL
);

ALTER TABLE klijentski_projekat ADD CONSTRAINT klijentskiprojekat_idp_un UNIQUE ( idp );

CREATE TABLE menadzer (
    idr INTEGER NOT NULL
);

ALTER TABLE menadzer ADD CONSTRAINT menadzer_pk PRIMARY KEY ( idr );

CREATE TABLE menadzer_klijent (
    idr INTEGER NOT NULL,
    idk INTEGER NOT NULL
);

ALTER TABLE menadzer_klijent ADD CONSTRAINT menazerklijent_pk PRIMARY KEY ( idr,
                                                                            idk );

CREATE TABLE praksa (
    idpk INTEGER NOT NULL,
    idr  INTEGER NOT NULL
);

ALTER TABLE praksa ADD CONSTRAINT praksa_pk PRIMARY KEY ( idr,
                                                          idpk );

CREATE TABLE praktikant (
    idpk   INTEGER NOT NULL,
    imepk  VARCHAR2(50),
    prezpk VARCHAR2(50)
);

ALTER TABLE praktikant ADD CONSTRAINT praktikant_pk PRIMARY KEY ( idpk );

CREATE TABLE projekat (
    idp    INTEGER NOT NULL,
    idfl   INTEGER,
    vrzp   NUMBER,
    nazivp VARCHAR2(50),
    datp   DATE,
    datk   DATE,
    tipp   VARCHAR2(30) NOT NULL
);

ALTER TABLE projekat
    ADD CONSTRAINT ch_inh_projekat CHECK ( tipp IN ( 'Interni_Projekat', 'Klijentski_Projekat' ) );

ALTER TABLE projekat ADD CONSTRAINT projekat_idp_un UNIQUE ( idp );

CREATE TABLE projekat_tehnologija (
    projekat_idp    INTEGER NOT NULL,
    tehnologija_idt INTEGER NOT NULL
);

ALTER TABLE projekat_tehnologija ADD CONSTRAINT projekat_tehnologija_pk PRIMARY KEY ( projekat_idp,
                                                                                      tehnologija_idt );

CREATE TABLE projekat_zaduzenje (
    idp INTEGER
        CONSTRAINT nnc_idp NOT NULL,
    idz INTEGER
        CONSTRAINT nnc_idz NOT NULL
);

ALTER TABLE projekat_zaduzenje ADD CONSTRAINT projekat_zaduzenje_pk PRIMARY KEY ( idp,
                                                                                  idz );

CREATE TABLE racunarski_sistem (
    idrs  INTEGER NOT NULL,
    idr   INTEGER NOT NULL,
    brkrs INTEGER,
    opsrs CLOB,
    memrs VARCHAR2(100),
    cpurs VARCHAR2(100),
    gpurs VARCHAR2(100)
);

ALTER TABLE racunarski_sistem ADD CONSTRAINT racunarskisistem_pk PRIMARY KEY ( idrs );

CREATE TABLE radnik (
    idr    INTEGER NOT NULL,
    idadr  INTEGER,
    pol    VARCHAR2(10),
    przr   VARCHAR2(50),
    mbrr   INTEGER NOT NULL,
    imer   VARCHAR2(50),
    emailr VARCHAR2(50) NOT NULL,
    telr   INTEGER,
    isr    VARCHAR2(50),
    tipr   VARCHAR2(20) NOT NULL,
    idfl   INTEGER
);

ALTER TABLE radnik
    ADD CHECK ( pol IN ( 'M', 'Z' ) );

ALTER TABLE radnik
    ADD CONSTRAINT ch_inh_radnik CHECK ( tipr IN ( 'Admin', 'Hr', 'Menadzer', 'Softverski_Inzenjer' ) );

ALTER TABLE radnik ADD CONSTRAINT radnik_pk PRIMARY KEY ( idr );

ALTER TABLE radnik ADD CONSTRAINT radnik__un UNIQUE ( mbrr );
ALTER TABLE radnik ADD CONSTRAINT radnik__un1 UNIQUE ( emailr );

CREATE TABLE saradjivana_firma (
    firma_idf  INTEGER NOT NULL,
    firma_idf1 INTEGER NOT NULL
);

ALTER TABLE saradjivana_firma ADD CONSTRAINT relation_20_pk PRIMARY KEY ( firma_idf,
                                                                          firma_idf1 );

CREATE TABLE softver (
    ids    INTEGER NOT NULL,
    nazivs VARCHAR2(100),
    opiss  VARCHAR2(200),
    lics   VARCHAR2(50),
    vrzs   NUMBER
);

ALTER TABLE softver ADD CONSTRAINT softver_pk PRIMARY KEY ( ids );

CREATE TABLE softverski_inzenjer (
    idr INTEGER NOT NULL
);

ALTER TABLE softverski_inzenjer ADD CONSTRAINT softverski_inzenjer_pk PRIMARY KEY ( idr );

CREATE TABLE tehnologija (
    idt    INTEGER NOT NULL,
    nazivt VARCHAR2(50) NOT NULL,
    vrzt   NUMBER
);

ALTER TABLE tehnologija ADD CONSTRAINT tehnologija_pk PRIMARY KEY ( idt );

CREATE TABLE test (
    idt   INTEGER NOT NULL,
    datpt DATE,
    datkt DATE
);

ALTER TABLE test ADD CONSTRAINT test_pk PRIMARY KEY ( idt );

CREATE TABLE test_praksa (
    praksa_idr  INTEGER NOT NULL,
    praksa_idpk INTEGER NOT NULL,
    test_idt    INTEGER NOT NULL
);

ALTER TABLE test_praksa
    ADD CONSTRAINT testpraksa_pk PRIMARY KEY ( praksa_idr,
                                               praksa_idpk,
                                               test_idt );

CREATE TABLE zaduzenje (
    idz    INTEGER NOT NULL,
    nazivz VARCHAR2(50),
    opisz  VARCHAR2(50)
);

ALTER TABLE zaduzenje ADD CONSTRAINT zaduzenje_pk PRIMARY KEY ( idz );

ALTER TABLE racunarski_sistem
    ADD CONSTRAINT admin_fk FOREIGN KEY ( idr )
        REFERENCES admin ( idr );

ALTER TABLE admin
    ADD CONSTRAINT admin_radnik_fk FOREIGN KEY ( idr )
        REFERENCES radnik ( idr );

ALTER TABLE firma
    ADD CONSTRAINT adresa_fk FOREIGN KEY ( idadr )
        REFERENCES adresa ( idadr );

ALTER TABLE filijala
    ADD CONSTRAINT adresa_fkv1 FOREIGN KEY ( idadr )
        REFERENCES adresa ( idadr );

ALTER TABLE radnik
    ADD CONSTRAINT adresa_fkv3 FOREIGN KEY ( idadr )
        REFERENCES adresa ( idadr );

ALTER TABLE projekat
    ADD CONSTRAINT filijala_fk FOREIGN KEY ( idfl )
        REFERENCES filijala ( idfl );

ALTER TABLE radnik
    ADD CONSTRAINT filijala_fkv1 FOREIGN KEY ( idfl )
        REFERENCES filijala ( idfl );

ALTER TABLE filijala
    ADD CONSTRAINT firma_fk FOREIGN KEY ( idf )
        REFERENCES firma ( idf );

ALTER TABLE saradjivana_firma
    ADD CONSTRAINT firma_fkv1 FOREIGN KEY ( firma_idf1 )
        REFERENCES firma ( idf );

ALTER TABLE saradjivana_firma
    ADD CONSTRAINT firma_fkv2 FOREIGN KEY ( firma_idf )
        REFERENCES firma ( idf );

ALTER TABLE bodovna_skala
    ADD CONSTRAINT hr_fk FOREIGN KEY ( idr )
        REFERENCES hr ( idr );

ALTER TABLE hr
    ADD CONSTRAINT hr_radnik_fk FOREIGN KEY ( idr )
        REFERENCES radnik ( idr );

ALTER TABLE interni_projekat
    ADD CONSTRAINT interniprojekat_projekat_fk FOREIGN KEY ( idp )
        REFERENCES projekat ( idp );

ALTER TABLE inzenjer_obavlja_zaduzenje
    ADD CONSTRAINT inzinjerprojekat_fk FOREIGN KEY ( inzinjerprojekat_idr,
                                                     inzinjerprojekat_idp )
        REFERENCES inzinjer_projekat ( idr,
                                       idp );

ALTER TABLE menadzer_klijent
    ADD CONSTRAINT klijent_fk FOREIGN KEY ( idk )
        REFERENCES klijent ( idk );

ALTER TABLE klijentski_projekat
    ADD CONSTRAINT klijent_fkv2 FOREIGN KEY ( idk )
        REFERENCES klijent ( idk );

ALTER TABLE klijentski_projekat
    ADD CONSTRAINT klijentskiprojekat_projekat_fk FOREIGN KEY ( idp )
        REFERENCES projekat ( idp );

ALTER TABLE menadzer_klijent
    ADD CONSTRAINT menadzer_fk FOREIGN KEY ( idr )
        REFERENCES menadzer ( idr );

ALTER TABLE menadzer
    ADD CONSTRAINT menadzer_radnik_fk FOREIGN KEY ( idr )
        REFERENCES radnik ( idr );

ALTER TABLE praksa
    ADD CONSTRAINT praktikant_fk FOREIGN KEY ( idpk )
        REFERENCES praktikant ( idpk );

ALTER TABLE projekat_tehnologija
    ADD CONSTRAINT projekat_fk FOREIGN KEY ( projekat_idp )
        REFERENCES projekat ( idp );

ALTER TABLE inzinjer_projekat
    ADD CONSTRAINT projekat_fkv2 FOREIGN KEY ( idp )
        REFERENCES projekat ( idp );

ALTER TABLE projekat_zaduzenje
    ADD CONSTRAINT projekat_fkv3 FOREIGN KEY ( idp )
        REFERENCES projekat ( idp );

ALTER TABLE inzenjer_obavlja_zaduzenje
    ADD CONSTRAINT projekatzaduzenje_fk FOREIGN KEY ( projekatzaduzenje_idp,
                                                      projekatzaduzenje_idz )
        REFERENCES projekat_zaduzenje ( idp,
                                        idz );

ALTER TABLE bodovna_skala
    ADD CONSTRAINT radnik_fk FOREIGN KEY ( idr2 )
        REFERENCES radnik ( idr );

ALTER TABLE interni_projekat
    ADD CONSTRAINT softver_fk FOREIGN KEY ( ids )
        REFERENCES softver ( ids );

ALTER TABLE inzinjer_projekat
    ADD CONSTRAINT softverski_inzenjer_fk FOREIGN KEY ( idr )
        REFERENCES softverski_inzenjer ( idr );

ALTER TABLE praksa
    ADD CONSTRAINT softverski_inzenjer_fkv1 FOREIGN KEY ( idr )
        REFERENCES softverski_inzenjer ( idr );

ALTER TABLE softverski_inzenjer
    ADD CONSTRAINT softverskiinzenjer_radnik_fk FOREIGN KEY ( idr )
        REFERENCES radnik ( idr );

ALTER TABLE projekat_tehnologija
    ADD CONSTRAINT tehnologija_fk FOREIGN KEY ( tehnologija_idt )
        REFERENCES tehnologija ( idt );

ALTER TABLE test_praksa
    ADD CONSTRAINT testpraksa_praksa_fk FOREIGN KEY ( praksa_idr,
                                                      praksa_idpk )
        REFERENCES praksa ( idr,
                            idpk );

ALTER TABLE test_praksa
    ADD CONSTRAINT testpraksa_test_fk FOREIGN KEY ( test_idt )
        REFERENCES test ( idt );

ALTER TABLE projekat_zaduzenje
    ADD CONSTRAINT zaduzenje_fk FOREIGN KEY ( idz )
        REFERENCES zaduzenje ( idz );

CREATE OR REPLACE TRIGGER arc_fkarc__softverski_inzenjer BEFORE
    INSERT OR UPDATE OF idr ON softverski_inzenjer
    FOR EACH ROW
DECLARE
    d VARCHAR2(20);
BEGIN
    SELECT
        a.tipr
    INTO d
    FROM
        radnik a
    WHERE
        a.idr = :new.idr;

    IF ( d IS NULL OR d <> 'Softverski_Inzenjer' ) THEN
        raise_application_error(-20223, 'FK SoftverskiInzenjer_Radnik_FK in Table Softverski_Inzenjer violates Arc constraint on Table Radnik - discriminator column TipR doesn''t have value ''Softverski_Inzenjer'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_menadzer BEFORE
    INSERT OR UPDATE OF idr ON menadzer
    FOR EACH ROW
DECLARE
    d VARCHAR2(20);
BEGIN
    SELECT
        a.tipr
    INTO d
    FROM
        radnik a
    WHERE
        a.idr = :new.idr;

    IF ( d IS NULL OR d <> 'Menadzer' ) THEN
        raise_application_error(-20223, 'FK Menadzer_Radnik_FK in Table Menadzer violates Arc constraint on Table Radnik - discriminator column TipR doesn''t have value ''Menadzer'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_hr BEFORE
    INSERT OR UPDATE OF idr ON hr
    FOR EACH ROW
DECLARE
    d VARCHAR2(20);
BEGIN
    SELECT
        a.tipr
    INTO d
    FROM
        radnik a
    WHERE
        a.idr = :new.idr;

    IF ( d IS NULL OR d <> 'Hr' ) THEN
        raise_application_error(-20223, 'FK Hr_Radnik_FK in Table Hr violates Arc constraint on Table Radnik - discriminator column TipR doesn''t have value ''Hr'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_admin BEFORE
    INSERT OR UPDATE OF idr ON admin
    FOR EACH ROW
DECLARE
    d VARCHAR2(20);
BEGIN
    SELECT
        a.tipr
    INTO d
    FROM
        radnik a
    WHERE
        a.idr = :new.idr;

    IF ( d IS NULL OR d <> 'Admin' ) THEN
        raise_application_error(-20223, 'FK Admin_Radnik_FK in Table Admin violates Arc constraint on Table Radnik - discriminator column TipR doesn''t have value ''Admin'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_interni_projekat BEFORE
    INSERT OR UPDATE OF idp ON interni_projekat
    FOR EACH ROW
DECLARE
    d VARCHAR2(30);
BEGIN
    SELECT
        a.tipp
    INTO d
    FROM
        projekat a
    WHERE
        a.idp = :new.idp;

    IF ( d IS NULL OR d <> 'Interni_Projekat' ) THEN
        raise_application_error(-20223, 'FK InterniProjekat_Projekat_FK in Table Interni_Projekat violates Arc constraint on Table Projekat - discriminator column TipP doesn''t have value ''Interni_Projekat'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc__klijentski_projekat BEFORE
    INSERT OR UPDATE OF idp ON klijentski_projekat
    FOR EACH ROW
DECLARE
    d VARCHAR2(30);
BEGIN
    SELECT
        a.tipp
    INTO d
    FROM
        projekat a
    WHERE
        a.idp = :new.idp;

    IF ( d IS NULL OR d <> 'Klijentski_Projekat' ) THEN
        raise_application_error(-20223, 'FK KlijentskiProjekat_Projekat_FK in Table Klijentski_Projekat violates Arc constraint on Table Projekat - discriminator column TipP doesn''t have value ''Klijentski_Projekat'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            27
-- CREATE INDEX                             1
-- ALTER TABLE                             67
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
